# Generated by Django 3.0.5 on 2022-03-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新日時')),
                ('poseter_url', models.TextField(blank=True, null=True, verbose_name='画像URL')),
                ('genre', models.CharField(max_length=128, verbose_name='ジャンル')),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('lv', models.CharField(max_length=128, verbose_name='レベル')),
                ('notes', models.BigIntegerField(blank=True, null=True, verbose_name='ノーツ')),
                ('bell', models.BigIntegerField(blank=True, null=True, verbose_name='ベル')),
                ('const', models.FloatField(blank=True, null=True, verbose_name='譜面定数')),
                ('bpm', models.IntegerField(blank=True, null=True, verbose_name='BPM')),
                ('difficulty', models.CharField(max_length=128, verbose_name='難易度')),
            ],
            options={
                'verbose_name': '楽曲情報',
                'verbose_name_plural': '楽曲情報',
            },
        ),
    ]
